"""Calibrated similarity thresholds per (encoder, language).

A naive 0.5 cosine-similarity cutoff performs at or near chance on most
encoder/language combinations. This module ships a starting-point
calibration table for five encoders across English, Hindi, and Hinglish,
plus :func:`calibrate` for fitting your own threshold on your own
labelled data.

Each shipped cell stores the cosine-similarity cutoff that maximized
correct-vs-wrong discrimination accuracy on a small benchmark (about 10
cases per cell, using a single English gold answer and full-sentence
candidate answers), along with the accuracy at that cutoff, the accuracy
at 0.5 for comparison, and the threshold-independent ROC AUC. These are
small-sample calibrations: treat them as a documented starting point and
prefer :func:`calibrate` on data from your own domain. The underlying
benchmark data is available through :mod:`vindex.datasets`.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

MURIL_MODEL_NAME = "google/muril-base-cased"

MURIL_WARNING = (
    "google/muril-base-cased scores ~0.99 cosine similarity on nearly "
    "everything -- correct answers, wrong answers, even different "
    "languages -- with std ~0.002. It cannot "
    "discriminate correct from wrong at any threshold. This is the "
    "encoder an Indian-language project reaches for first, because "
    "'Multilingual Representations for Indian Languages' sounds like "
    "exactly the right tool -- it is the trap. See the HindiWiC "
    "finding (Dairkee & Dubossarsky, 2024, 'Strengthening the WiC: New "
    "polysemy dataset in Hindi and lack of cross lingual transfer', "
    "LREC-COLING 2024, https://github.com/haimdub/HindiWiC): MuRIL scores 55% "
    "zero-shot on Hindi word-sense disambiguation, chance level for a "
    "2-way task, reaching 90% only after Hindi-specific fine-tuning it "
    "does not ship with. Use mpnet or e5 instead, or fine-tune MuRIL "
    "yourself before relying on it."
)

DEFAULT_ENCODER = "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"


@dataclass(frozen=True, slots=True)
class CalibratedThreshold:
    """One (encoder, language) calibration cell.

    Attributes:
        threshold: Cosine-similarity cutoff that maximized correct-vs-wrong
            discrimination accuracy for this cell.
        accuracy_at_threshold: Discrimination accuracy at ``threshold``.
            This is an in-sample fit and can look acceptable even when the
            cell has no real discrimination; check ``roc_auc``.
        accuracy_at_default: Discrimination accuracy at the naive default
            of 0.5, for comparison.
        n_cases: Number of (correct, wrong) case pairs the cell was fitted
            on (the smaller side, for :func:`calibrate`).
        warnings: Non-fatal signals that the fit may not be trustworthy.
            See :func:`calibrate` for what is checked. An empty tuple means
            none of those checks fired, not that the cell discriminates.
        roc_auc: Threshold-independent ROC AUC for the cell (0.5 = chance,
            below 0.5 = inverted). Set for every shipped cell; ``None`` for
            results returned by :func:`calibrate`.
    """

    threshold: float
    accuracy_at_threshold: float
    accuracy_at_default: float
    n_cases: int = 10
    warnings: tuple[str, ...] = ()
    roc_auc: float | None = None


# Calibration data -- generated by running calibrate() on the benchmark's
# per-case scores; do not edit by hand.
#
# An empty `warnings` tuple means a cell passed calibrate()'s own guards,
# which check in-sample fitted accuracy only. Use `roc_auc` to judge
# whether a cell has real discrimination: e.g. multilingual-e5-base/hi
# fits at 0.632 accuracy with no warning but has ROC AUC 0.500 (chance).
CALIBRATION_TABLE: dict[str, dict[str, CalibratedThreshold]] = {
    "sentence-transformers/all-MiniLM-L6-v2": {
        "en": CalibratedThreshold(
            0.8629738688468933, 0.65, 0.5, n_cases=10, warnings=(), roc_auc=0.6
        ),
        "hi": CalibratedThreshold(
            0.10077689588069916,
            0.631578947368421,
            0.5263157894736842,
            n_cases=9,
            warnings=(),
            roc_auc=0.5888888888888889,
        ),
        "hinglish": CalibratedThreshold(
            0.35428088903427124, 0.75, 0.6, n_cases=10, warnings=(), roc_auc=0.75
        ),
    },
    "sentence-transformers/LaBSE": {
        "en": CalibratedThreshold(
            0.553279459476471,
            0.5,
            0.5,
            n_cases=10,
            warnings=(
                "fitted accuracy (0.50) is at or below chance -- this data may not "
                "separate correct from wrong at all, or the correct/wrong lists may "
                "be swapped.",
            ),
            roc_auc=0.06999999999999998,
        ),
        "hi": CalibratedThreshold(
            0.5384654402732849,
            0.47368421052631576,
            0.47368421052631576,
            n_cases=9,
            warnings=(
                "fitted accuracy (0.47) is at or below chance -- this data may not "
                "separate correct from wrong at all, or the correct/wrong lists may "
                "be swapped.",
            ),
            roc_auc=0.16666666666666666,
        ),
        "hinglish": CalibratedThreshold(
            0.4422089755535126, 0.75, 0.65, n_cases=10, warnings=(), roc_auc=0.7300000000000001
        ),
    },
    "intfloat/multilingual-e5-base": {
        "en": CalibratedThreshold(
            0.8811413049697876, 0.9, 0.5, n_cases=10, warnings=(), roc_auc=0.86
        ),
        "hi": CalibratedThreshold(
            0.8806519508361816,
            0.631578947368421,
            0.47368421052631576,
            n_cases=9,
            warnings=(),
            roc_auc=0.49999999999999994,
        ),
        "hinglish": CalibratedThreshold(
            0.8469548225402832, 0.75, 0.5, n_cases=10, warnings=(), roc_auc=0.68
        ),
    },
    MURIL_MODEL_NAME: {
        "en": CalibratedThreshold(
            0.9957686066627502,
            0.5,
            0.5,
            n_cases=10,
            warnings=(
                "fitted accuracy (0.50) is at or below chance -- this data may not "
                "separate correct from wrong at all, or the correct/wrong lists may "
                "be swapped.",
            ),
            roc_auc=0.0,
        ),
        "hi": CalibratedThreshold(
            0.992067813873291,
            0.47368421052631576,
            0.47368421052631576,
            n_cases=9,
            warnings=(
                "fitted accuracy (0.47) is at or below chance -- this data may not "
                "separate correct from wrong at all, or the correct/wrong lists may "
                "be swapped.",
            ),
            roc_auc=0.1111111111111111,
        ),
        "hinglish": CalibratedThreshold(
            0.9907472133636475,
            0.6,
            0.5,
            n_cases=10,
            warnings=(),
            roc_auc=0.43999999999999995,
        ),
    },
    "sentence-transformers/paraphrase-multilingual-mpnet-base-v2": {
        "en": CalibratedThreshold(
            0.8324964046478271, 0.85, 0.5, n_cases=10, warnings=(), roc_auc=0.9299999999999999
        ),
        "hi": CalibratedThreshold(
            0.8738334774971008,
            0.7368421052631579,
            0.47368421052631576,
            n_cases=9,
            warnings=(),
            roc_auc=0.7222222222222222,
        ),
        "hinglish": CalibratedThreshold(
            0.41423243284225464, 0.8, 0.7, n_cases=10, warnings=(), roc_auc=0.7300000000000001
        ),
    },
}


def get_threshold(encoder_name: str, language: str) -> CalibratedThreshold:
    """Look up the shipped calibration for an encoder and language.

    Args:
        encoder_name: Hugging Face model id of the encoder.
        language: One of ``"en"``, ``"hi"``, ``"hinglish"``.

    Returns:
        The shipped :class:`CalibratedThreshold` for that cell.

    Raises:
        KeyError: If the encoder or language is not in the shipped table.
            Callers should fall back to 0.5 (or :func:`calibrate`)
            explicitly rather than have this guess.
    """
    try:
        by_language = CALIBRATION_TABLE[encoder_name]
    except KeyError:
        raise KeyError(
            f"no shipped calibration for encoder {encoder_name!r}. "
            f"Known encoders: {sorted(CALIBRATION_TABLE)}. "
            "Use calibrate() to fit your own threshold."
        ) from None
    try:
        return by_language[language]
    except KeyError:
        raise KeyError(
            f"no shipped calibration for language {language!r} on "
            f"encoder {encoder_name!r}. Known languages: "
            f"{sorted(by_language)}. Use calibrate() to fit your own "
            "threshold."
        ) from None


def calibrate(
    similarities_correct: list[float], similarities_wrong: list[float]
) -> CalibratedThreshold:
    """Fit a similarity threshold on your own labelled data.

    Sweeps every observed similarity value as a candidate threshold and
    returns the one that maximizes accuracy (correct pairs scoring
    ``>= threshold``, wrong pairs scoring ``< threshold``).

    A result is always returned for structurally valid input, even when
    the fit looks poor; problems are reported in the result's
    ``warnings`` tuple instead:

    - fewer than 5 cases on either side ("too few cases to trust this fit");
    - scores outside cosine similarity's valid [-1, 1] range;
    - fitted accuracy at or below chance (0.5), which may mean the data
      does not separate correct from wrong, or the lists are swapped.

    Always check ``warnings`` before trusting a threshold fitted on a
    small or unfamiliar dataset.

    Args:
        similarities_correct: Cosine similarities for known-correct pairs.
        similarities_wrong: Cosine similarities for known-wrong pairs.

    Returns:
        A :class:`CalibratedThreshold` with ``roc_auc`` set to ``None``.

    Raises:
        ValueError: If either list is empty, or if any score is NaN (a NaN
            score indicates corrupted upstream input, such as a bad cached
            embedding, and is never silently fitted around).
    """
    if not similarities_correct or not similarities_wrong:
        raise ValueError(
            "calibrate() needs at least one correct and one wrong "
            "similarity score to fit a threshold."
        )
    if any(math.isnan(s) for s in similarities_correct + similarities_wrong):
        raise ValueError(
            "calibrate() received a NaN similarity score -- this indicates "
            "corrupted input (e.g. a bad cached embedding or fp16 overflow "
            "upstream), not a valid similarity to fit against. Remove NaN "
            "entries and investigate their source before calibrating."
        )

    n = len(similarities_correct) + len(similarities_wrong)
    candidates = sorted(set(similarities_correct) | set(similarities_wrong))

    best_threshold = candidates[0]
    best_correct = sum(1 for s in similarities_correct if s >= best_threshold)
    best_wrong = sum(1 for s in similarities_wrong if s < best_threshold)
    best_accuracy = (best_correct + best_wrong) / n

    for threshold in candidates[1:]:
        n_correct = sum(1 for s in similarities_correct if s >= threshold)
        n_wrong = sum(1 for s in similarities_wrong if s < threshold)
        accuracy = (n_correct + n_wrong) / n
        if accuracy > best_accuracy:
            best_threshold, best_accuracy = threshold, accuracy

    accuracy_at_default = (
        sum(1 for s in similarities_correct if s >= 0.5)
        + sum(1 for s in similarities_wrong if s < 0.5)
    ) / n

    warnings: list[str] = []
    n_cases = min(len(similarities_correct), len(similarities_wrong))
    if n_cases < 5:
        warnings.append(
            f"only {n_cases} case(s) on the smaller side -- too few cases to "
            "trust this fit; a threshold from this few points can look "
            "perfect by chance."
        )
    if any(s < -1.0 or s > 1.0 for s in similarities_correct + similarities_wrong):
        warnings.append(
            "some scores are outside [-1, 1] -- is this actually cosine "
            "similarity? calibrate() assumes cosine similarity but does "
            "not enforce it."
        )
    if best_accuracy <= 0.5:
        warnings.append(
            f"fitted accuracy ({best_accuracy:.2f}) is at or below chance -- "
            "this data may not separate correct from wrong at all, or the "
            "correct/wrong lists may be swapped."
        )

    return CalibratedThreshold(
        threshold=best_threshold,
        accuracy_at_threshold=best_accuracy,
        accuracy_at_default=accuracy_at_default,
        n_cases=n_cases,
        warnings=tuple(warnings),
    )
